### ISSUE TITLE
[Bug] Weird canvas display after zooming

### ISSUE THREAD

**Issue by adepierre** [thedmd/imgui-node-editor#260]
With latest version, canvas centering is broken when zooming. Instead of taking the whole area, the canvas shrinks with black borders around. I think the faulty commit is 6e662a4f61f8fae439026908e5f76155d91c5dcb but I'm not sure why. Automatic "fit to content" with F is also not correct, with extreme zoom level.

Imgui version tested with: 1.89.9

![image](https://github.com/thedmd/imgui-node-editor/assets/24371370/78e71d4a-d85c-4647-a453-011d76f5c09c)

![image](https://github.com/thedmd/imgui-node-editor/assets/24371370/7d20fc5a-4c64-48c6-8780-f3da9fec5937)

**Comment by w0utert** [comment]
Same for me. I'm extremely glad I found this issue because I was almost set to go on an epic debug quest to find out how my own DPI/mouse scaling code would be broken. I'm using an ImGui 1.89-WIP snapshot from master with Vulkan backend.

imgui-node-editor v0.9.2-stable works fine so I've reverted to that for now.

**Comment by thedmd** [comment]
I tried to reproduce with latest ImGui but without luck.
Can you @adepierre or you @w0utert provide a way to reproduce that behavior?

**Comment by adepierre** [comment]
I tried to make a small standalone cmake project to reproduce the error. It's using imgui 1.89.9 and node editor master branch [084736a](https://github.com/thedmd/imgui-node-editor/commit/084736a4f2b5185e883aa50d5922cbe03c18d3b8). To reproduce: launch the repro project, zoom/unzoom/press F.

[repro.zip](https://github.com/thedmd/imgui-node-editor/files/12907970/repro.zip)

**Comment by thedmd** [comment]
Thank you very much. It is fixed now on `master` and `develop`

**Comment by lksrb** [comment]
Hi, it seems that this is still an issue. I just integrated node editor with this sample code. 

![image](https://github.com/thedmd/imgui-node-editor/assets/26255023/18d2a21d-1e7d-4706-978c-b47d6b2c8923)

https://github.com/thedmd/imgui-node-editor/assets/26255023/1dd8e31c-5ce8-49d2-ba9e-234aa5f06f29
